sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_install:
	# Version check, cause we need the best npm version/latest
	- npm install -g npm
	- npm install chalk underscore-plus request fs-extra