// Generated by CoffeeScript 1.9.3
(function() {
  var Console, _, chalk;

  chalk = require('chalk');

  _ = require('underscore-plus');

  Console = require('./consoleMessages');

  _.extend(Console, it, (function(_this) {
    return function(msg) {
      var it;
      it = chalk.blue.underline;
      return console.log(it(msg));
    };
  })(this));

  module.exports = Classy.Highlight;

}).call(this);
