// Generated by CoffeeScript 1.9.3
(function() {
  var Classy, chalk;

  chalk = require('chalk');

  Classy = require('../specs/Classy');

  Classy.Highlight = function(msg) {
    var it;
    it = chalk.blue.underline;
    return console.log(it(msg));
  };

  module.exports = Classy.Highlight;

}).call(this);
