// Generated by CoffeeScript 1.9.3
(function() {
  var Classy, Random;

  Classy = require('../specs/Classy');

  Random = require('../specs/Random');

  Classy.MagicBall = function(question) {
    var phrases;
    phrases = ["I'm not so sure", "maybe", "ask another time", "just give up", "ask your friend", "maybe try debugging", "try again", "try some other time", "try next tuesday", "find another magic 8 ball"];
    return question + ("\n Answer: " + (Random(phrases)));
  };

  module.exports = Classy.MagicBall;

}).call(this);
