// Generated by CoffeeScript 1.9.3
(function() {
  var Classy,
    slice = [].slice;

  Classy = require('../specs/Classy');

  Classy.Maths = (function(_this) {
    return function() {
      var args;
      args = 1 <= arguments.length ? slice.call(arguments, 0) : [];
      return eval.apply(null, args);
    };
  })(this);

  module.exports = Classy.Maths;

}).call(this);
