// Generated by CoffeeScript 1.9.3
(function() {
  var Classy, key, tail,
    slice = [].slice;

  Classy = require('../specs/Classy');

  key = {
    bold: "**",
    underline: "_",
    h1: "#",
    h2: "##",
    h3: "###",
    h4: "####",
    h5: '#####',
    h6: '######',
    blockquote: ">",
    ahref: "@"
  };

  tail = [1, 2, 3, 4, 5, 6];

  Classy.md = function() {
    var i, len, number, str;
    str = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    if (str == null) {
      str = str.substring(0);
    }
    switch (str) {
      case str === key.bold:
        str.replace(key.bold, '<b>').substring(-1).replace(key.bold, '</b>');
        break;
      case str === key.underline:
        str.replace(key.underline, "<u>").substring(-1).replace(key.underline, "</u>");
        break;
      case str === key.tail:
        for (i = 0, len = tail.length; i < len; i++) {
          number = tail[i];
          str.replace(tail[number], "<h" + number + ">").substring(-1).replace(tail[number], "</h" + number + ">");
        }
        break;
      case str === key.blockquote:
        str.replace(key.blockquote, '<blockquote>').substring(-1).replace(key.blockquote, "</blockquote>");
        break;
      case str === key.ahref:
        str.replace(key.ahref, '<a href="#">').substring(-1).replace("</a>");
        break;
    }
    if (typeof str !== "String") {

    }
  };

  module.exports = Classy.md;

}).call(this);
