// Generated by CoffeeScript 1.9.3
(function() {
  var Classy, _;

  _ = require('underscore-plus');

  Classy = require('../specs/Classy');

  Classy.ClassCut = function(_class, opts, from, to, _by) {
    var $idem, $scope, i, len, template;
    $scope = _.range(from, to, _by);
    for (i = 0, len = $scope.length; i < len; i++) {
      $idem = $scope[i];
      template = _class + "-" + $idem + " {\n	" + opts + "\n}";
    }
    return template;
  };

  module.exports = Classy.ClassCut;

}).call(this);
