// Generated by CoffeeScript 1.9.3
(function() {
  "use strict";
  var Classy, Console, Random, _;

  Classy = require('../specs/Classy');

  Random = require('../specs/Random');

  _ = require('underscore-plus');

  Console = require('./consoleMessages');


  /*
   * @param {ducky} Your buddy in helping you code
   * @param {questions} Set of questions to help you debug
   * @param {genie} Extension of the `magic8ball` class
   */

  Classy.RubberDucky = function(_prompt) {
    var questions;
      constructor: function(questions, ducky, genie, args) {
        if (args == null) {
          args = argv[0];
        }
        this.questions = [];
        this.ducky = {};
        this.genie = {};
        this.args = argv[0];
      }
    questions = ["did you make sure that your arguments aren't spelled wrong?", "check stackoverflow", "google it", "cache overflow maybe?", "make sure you have the right dependencies", "did you install your test dependencies?", "check if your arrows are right", "did you compile it through babel first?", "is your code ES6/7? maybe go compile first"];
    this.ducky.prompt = Random(questions);
    this.genie.text = _prompt + "\n\n" + this.ducky.prompt;
    return this.genie.text;
  };

}).call(this);
