// Generated by CoffeeScript 1.9.3
(function() {
  var Classy, Console, _,
    slice = [].slice;

  Classy = require('../specs/Classy');

  Console = require('./consoleMessages');

  _ = require('underscore-plus');

  Classy.Svg = function() {
    var compile, opts;
    opts = 1 <= arguments.length ? slice.call(arguments, 0) : [];
    if (_.isObject.apply(_, opts)) {
      compile = _.template("<svg class=\"<% _classname %>\n	width=\"<% w %>\"\n	height=\"<% h %>\"\n	shape=\"<% shape %>\"\n	cy=\"<% cy %>\"\n	cx=\"<% cx %>\"\n	rx=\"<% rx %>\"\n	ry=\"<% ry %>\"\n	style=\"<% style %>\"");
      return Svg(compile.apply(null, opts));
    } else {
      Console.error("!! Errror!!!");
    }
  };

  module.exports = Classy.Svg;

}).call(this);
