// Generated by CoffeeScript 1.9.3
(function() {
  var Classy, _;

  Classy = require('../specs/Classy');

  _ = require('underscore-plus');

  Classy.unquote = function(str) {
    if (typeof str === "String") {
      return _.escape(str);
    }
  };

  module.exports = Classy.unquote;

}).call(this);
